# Compulsory parameters
Number of DAGs: 3
Initial seed: 0
Number of nodes: 30
Number of entry nodes: 2
In-degree:
  Min: 1
  Max: 2
Out-degree:
  Min: 1
  Max: 2
Execution time:
  Min: 2
  Max: 70
  Use list: [2, 3, 4, 5]

# Optional parameters
Force merge to exit nodes:
  Number of exit nodes: 3
Use communication time:
  Min: 2
  Max: 3
  Use list: [2, 3, 4, 5]
Use multi-period:
  Periodic type: 'All'
  Descendants have larger period: True
  Max ratio of execution time to period: 1
  Min: 10
  Max: 30
  Use list: [10, 20, 30, 40]
