# Compulsory parameters
Number of DAGs: 1
Initial seed: 0
Number of nodes: 50
Number of entry nodes: 3
In-degree:
  Min: 1
  Max: 2
Out-degree:
  Min: 1
  Max: 2
Execution time:
  Min: 2
  Max: 70
  Use list: [2, 3, 4, 5]

# Optional parameters
Force merge to exit nodes:
  Number of exit nodes: 1
Use communication time:
  Min: 2
  Max: 3
  Use list: [2, 3, 4, 5]
Use multi-period:
  Periodic type: 'All'
  Descendants have smaller period: True
  Min: 10
  Max: 30
  Use list: [10, 20, 30, 40]
  