Seed: 0
Number of DAGs: 50
Generation method: "Fan-in/Fan-out"

Graph structure:
  Number of nodes:
    Random: (10, 100, 10)
  In-degree:
    Random: [1, 2, 3]
  Out-degree:
    Random: [1, 2, 3]
  Number of entry nodes:
    Combination: [2, 3, 4, 5]
  Number of exit nodes:
    Fixed: 1

Properties:
  Execution time:
    Random: (1, 50, 1)
  Communication time:
    Random: [1, 2, 3, 4, 5]
  End-to-end deadline:
    Ratio of deadline to critical path:
      Random: (1.0, 1.5, 0.1)
  Period:
    Periodic type: "All"
    Entry node periods:
      Combination: [10, 100]
    Exit node periods:
      Fixed: 10
    Offset:
      Random: (1, 5, 1)
    Total utilization:
      Combination: (0.7, 1.5, 0.1)

Output formats:
  Naming of combination directory: "Abbreviation"
  DAG:
    YAML: True
    JSON: False
    XML: False
    DOT: False
  Figure:
    Draw legend: False
    PNG: True
    SVG: True
    EPS: False
    PDF: False
