# Compulsory parameters
Number of DAGs: 3
Initial seed: 0
Number of nodes: 20
Number of chains: 5
Chain length:
  Min: 3
  Max: 7
Chain width:
  Min: 1
  Max: 2
Execution time:
  Min: 2
  Max: 70
  Use list: [2, 3, 4, 5]

# Optional parameters
Vertically link chains:
  Number of entry nodes: 2
  Max level of vertical links: 3
Merge chains:
  Number of exit nodes: 1
  Middle of chain: False
  Exit node: False
  Head of chain: True
Use end-to-end deadline:
  Ratio of deadlines to critical path length: 1.2
  # Ratio of deadlines to max period: 1.0
Use communication time:
  Min: 2
  Max: 3
  Use list: [2, 3, 4, 5]
Use multi-period:
  Periodic type: 'Chain'
  Min: 10
  Max: 30
  Use list: [10, 20, 30, 40]
  Entry node periods: [20, 40]
  Exit node periods: [30]
  Max ratio of execution time to period: 0.8
  Descendants have larger period: False

# Output formats
DAG format:
  yaml: True
  json: False
  xml: False
  dot: False
Figure format:
  pdf: False
  png: True
  svg: False
