# Compulsory parameters
Number of DAGs: 10
Initial seed: 0
Number of nodes: 10
Number of chains: 5
Chain length:
  Min: 1
  Max: 7
Chain width:
  Min: 1
  Max: 2
Execution time:
  Min: 10
  Max: 50

# Optional parameters
Vertically link chains:
  Number of entry nodes: 5
  Max level of vertical links: 2
Merge chains:
  Number of exit nodes: 2
  Middle of chain: True
  Exit node: True
  Head of chain: True
# Use end-to-end deadline:
#   Ratio of deadlines to critical path length: 1.2
#   Ratio of deadlines to max period: 1.0
Use communication time:
  Min: 1
  Max: 10
Use multi-period:
  Periodic type: 'All'
  Use list: [10, 20, 30, 40, 50, 60, 70, 80]
  # Entry node periods: [10, 100]
  # Exit node periods: [10]
  Max ratio of execution time to period: 1.0
  # Descendants have larger period: True

# Output formats
DAG format:
  yaml: False
  json: False
  xml: False
  dot: True
Figure format:
  pdf: True
  png: False
  svg: False
