# Compulsory parameters
Number of DAGs: 1
Initial seed: 0
Number of nodes: 50
Number of chains: 8
Chain length:
  Min: 2
  Max: 10
Chain width:
  Min: 1
  Max: 4
Execution time:
  Min: 2
  Max: 200

# Optional parameters
Vertically link chains:
  Number of entry nodes: 5
  Max level of vertical links: 5
Merge chains:
  Number of exit nodes: 1
  Middle of chain: False
  Exit node: True
  Head of chain: True
Use end-to-end deadline:
  Ratio of deadlines to critical path length: 1.2
  # Ratio of deadlines to max period: 1.0
Use communication time:
  Min: 2
  Max: 20
Use multi-period:
  Periodic type: 'Chain'
  Min: 20
  Max: 400
  # Entry node periods: [20, 40]
  # Exit node periods: [30]
  Max ratio of execution time to period: 0.8
  Descendants have larger period: True

# Output formats
DAG format:
  yaml: True
  json: False
  xml: False
  dot: False
Figure format:
  pdf: False
  png: True
  svg: False
