### Compulsory parameters
Number of DAGs: 10
Seed: 0
Number of nodes:
  Combination: (start=10, stop=20, step=2)
Number of chains:
  Combination: [2, 3, 4]
Chain length:
  Random: (1, 7, 1)
Chain width:
  Random: [1, 2, 3]
Execution time:
  Random: (1, 50, 1)

### Optional parameters
# Vertically link chains:
#   Number of entry nodes:
#     Fixed: 2
Merge chains:
  Number of exit nodes:
    Fixed: 1
  Middle of chain: False
  Exit node: True
  Head of chain: False
Use end-to-end deadline:
  Ratio of deadlines to max period:
    Random: (1.0, 1.5, 0.1)
Use communication time:
  Random: [2, 3, 4, 5]
Use multi-period:
  Periodic type: 'Chain'
  Period:
    Random: [10, 20, 30, 40, 50, 60]
  Entry node periods:
    Random: [50, 100]
  Exit node periods:
    Fixed: 10
  Max ratio of execution time to period:
    Random: (0.8, 1.0, 0.1)

### Output formats
DAG format:
  yaml: True
  json: False
  xml: False
  dot: False
Figure format:
  pdf: False
  png: False
  svg: False
  eps: True
  Draw legend: False
Naming of combination directory: 'Abbreviation'
